### ISSUE TITLE
cannot import name 'enums' from 'google.cloud.datacatalog'

### ISSUE THREAD

**Issue by peteratemarsys** [GoogleCloudPlatform/datacatalog-templates#2]
Hi!

I'm not able to run `create_template.py` due to an import error.

I'm running python 3.8 and `google-cloud-datacatalog==2.0.0`.

```
Traceback (most recent call last):
  File "create_template.py", line 19, in <module>
    from google.cloud.datacatalog import DataCatalogClient, enums, types
ImportError: cannot import name 'enums' from 'google.cloud.datacatalog' (/Users/xxxx/.pyenv/versions/3.8.2/lib/python3.8/site-packages/google/cloud/datacatalog/__init__.py)
```

I've also tried changing this line `from google.cloud.datacatalog import DataCatalogClient, enums, types` to
- `from google.cloud.datacatalog_v1 import DataCatalogClient, enums, types` and to
- `from google.cloud.datacatalog_v1beta1 import DataCatalogClient, enums, types`

but none worked.

**Comment by igor-devoteam** [comment]
The API changed without any update to this. 

instead of importing `enums` and `types` import the methods next level down. `FieldType`, `TagTemplate`

This fixed the import error for me, but I am running into further issues and going to have to try another approach than this python library which seems broken. 

Also see this script here : https://cloud.google.com/data-catalog/docs/quickstart-tagging

**Comment by shirleycohen** [comment]
Fixed a few months back
